# Generated by Django 3.2.16 on 2023-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='filenamepdf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='firstrecordpdf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='lastrecordpdf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='totalaccountspdf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='totalpagespdf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
