# Generated by Django 3.2.16 on 2023-03-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_auto_20230307_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='programnamepdf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
